apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter-ray1
  labels:
    app: jupyter-ray1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter-ray1
  template:
    metadata:
      labels:
        app: jupyter-ray1
    spec:
      containers:
      - name: minimal-notebook
        #image: jupyter/minimal-notebook:python-3.9.13
        image: jupyter/minimal-notebook:python-3.10.11
        ports:
        - containerPort: 8888
        command: ["start-notebook.sh"]
        args: ["--NotebookApp.token=''"]
---
kind: Service
apiVersion: v1
metadata:
  name: jupyter-ray1
spec:
  type: NodePort
  selector:
    app: jupyter-ray1
  ports:
  - protocol: TCP
    nodePort: 30041
    port: 8888
    targetPort: 8888

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter-ray2
  labels:
    app: jupyter-ray2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter-ray2
  template:
    metadata:
      labels:
        app: jupyter-ray2
    spec:
      containers:
      - name: minimal-notebook
        #image: jupyter/minimal-notebook:python-3.9.13
        image: jupyter/minimal-notebook:python-3.10.11
        ports:
        - containerPort: 8888
        command: ["start-notebook.sh"]
        args: ["--NotebookApp.token=''"]
---
kind: Service
apiVersion: v1
metadata:
  name: jupyter-ray2
spec:
  type: NodePort
  selector:
    app: jupyter-ray2
  ports:
  - protocol: TCP
    nodePort: 30042
    port: 8888
    targetPort: 8888

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter-ray3
  labels:
    app: jupyter-ray3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter-ray3
  template:
    metadata:
      labels:
        app: jupyter-ray3
    spec:
      containers:
      - name: minimal-notebook
        #image: jupyter/minimal-notebook:python-3.9.13
        image: jupyter/minimal-notebook:python-3.10.11
        ports:
        - containerPort: 8888
        command: ["start-notebook.sh"]
        args: ["--NotebookApp.token=''"]
---
kind: Service
apiVersion: v1
metadata:
  name: jupyter-ray3
spec:
  type: NodePort
  selector:
    app: jupyter-ray3
  ports:
  - protocol: TCP
    nodePort: 30043
    port: 8888
    targetPort: 8888


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter-ray4
  labels:
    app: jupyter-ray4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter-ray4
  template:
    metadata:
      labels:
        app: jupyter-ray4
    spec:
      containers:
      - name: minimal-notebook
        #image: jupyter/minimal-notebook:python-3.9.13
        image: jupyter/minimal-notebook:python-3.10.11
        ports:
        - containerPort: 8888
        command: ["start-notebook.sh"]
        args: ["--NotebookApp.token=''"]
---
kind: Service
apiVersion: v1
metadata:
  name: jupyter-ray4
spec:
  type: NodePort
  selector:
    app: jupyter-ray4
  ports:
  - protocol: TCP
    nodePort: 30044
    port: 8888
    targetPort: 8888
