{
 "title": "Serve Deployment Dashboard",
 "tags": [ "rayVersion:2.6.3" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Deployment",
    "query": {
     "query": "label_values(ray_serve_deployment_replica_healthy{}, deployment)"
    }
   },
   {
    "name": "Replica",
    "query": {
     "query": "label_values(ray_serve_deployment_replica_healthy{deployment=~\"$Deployment\",}, replica)"
    }
   },
   {
    "name": "Route",
    "query": {
     "query": "label_values(ray_serve_deployment_request_counter{deployment=~\"$Deployment\",}, route)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Replicas per deployment",
   "type": "graph",
   "description": "Number of replicas per deployment. Ignores \"Route\" variable.",
   "gridPos": { "x": 0, "y": 0, "w": 8, "h": 8 },
   "yaxes": [
    { "format": "replicas" }
   ],
   "targets": [
    {
     "expr": "sum(ray_serve_deployment_replica_healthy{deployment=~\"$Deployment\",replica=~\"$Replica\",}) by (deployment)",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "QPS per replica",
   "type": "graph",
   "description": "QPS for each replica.",
   "gridPos": { "x": 8, "y": 0, "w": 8, "h": 8 },
   "yaxes": [
    { "format": "qps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ray_serve_deployment_request_counter{route=~\"$Route\",route!~\"/-/.*\",deployment=~\"$Deployment\",replica=~\"$Replica\",}[5m])) by (deployment, replica)",
     "legendFormat": "{{replica}}"
    }
   ]
  },
  {
   "title": "Error QPS per replica",
   "type": "graph",
   "description": "Error QPS for each replica.",
   "gridPos": { "x": 16, "y": 0, "w": 8, "h": 8 },
   "yaxes": [
    { "format": "qps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ray_serve_deployment_error_counter{route=~\"$Route\",route!~\"/-/.*\",deployment=~\"$Deployment\",replica=~\"$Replica\",}[5m])) by (deployment, replica)",
     "legendFormat": "{{replica}}"
    }
   ]
  },
  {
   "title": "P50 latency per replica",
   "type": "graph",
   "description": "P50 latency per replica.",
   "gridPos": { "x": 0, "y": 1, "w": 8, "h": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(ray_serve_deployment_processing_latency_ms_bucket{route=~\"$Route\",route!~\"/-/.*\",deployment=~\"$Deployment\",replica=~\"$Replica\",}[5m])) by (deployment, replica, le))",
     "legendFormat": "{{replica}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(ray_serve_deployment_processing_latency_ms_bucket{route=~\"$Route\",route!~\"/-/.*\",deployment=~\"$Deployment\",replica=~\"$Replica\",}[5m])) by (le))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "P90 latency per replica",
   "type": "graph",
   "description": "P90 latency per replica.",
   "gridPos": { "x": 8, "y": 1, "w": 8, "h": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(ray_serve_deployment_processing_latency_ms_bucket{route=~\"$Route\",route!~\"/-/.*\",deployment=~\"$Deployment\",replica=~\"$Replica\",}[5m])) by (deployment, replica, le))",
     "legendFormat": "{{replica}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(ray_serve_deployment_processing_latency_ms_bucket{route=~\"$Route\",route!~\"/-/.*\",deployment=~\"$Deployment\",replica=~\"$Replica\",}[5m])) by (le))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "P99 latency per replica",
   "type": "graph",
   "description": "P99 latency per replica.",
   "gridPos": { "x": 16, "y": 1, "w": 8, "h": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(ray_serve_deployment_processing_latency_ms_bucket{route=~\"$Route\",route!~\"/-/.*\",deployment=~\"$Deployment\",replica=~\"$Replica\",}[5m])) by (deployment, replica, le))",
     "legendFormat": "{{replica}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(ray_serve_deployment_processing_latency_ms_bucket{route=~\"$Route\",deployment=~\"$Deployment\",replica=~\"$Replica\",}[5m])) by (le))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Queue size per deployment",
   "type": "graph",
   "description": "Number of requests queued per deployment. Ignores \"Replica\" and \"Route\" variable.",
   "gridPos": { "x": 0, "y": 2, "w": 8, "h": 8 },
   "yaxes": [
    { "format": "requests" }
   ],
   "targets": [
    {
     "expr": "sum(ray_serve_deployment_queued_queries{deployment=~\"$Deployment\",replica=~\"$Replica\",}) by (deployment)",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Pending requests per replica",
   "type": "graph",
   "description": "Pending requests for each replica.",
   "gridPos": { "x": 8, "y": 2, "w": 8, "h": 8 },
   "yaxes": [
    { "format": "requests" }
   ],
   "targets": [
    {
     "expr": "sum(ray_serve_replica_pending_queries{deployment=~\"$Deployment\",replica=~\"$Replica\",}) by (deployment, replica)",
     "legendFormat": "{{replica}}"
    }
   ]
  },
  {
   "title": "Running requests per replica",
   "type": "graph",
   "description": "Current running requests for each replica.",
   "gridPos": { "x": 16, "y": 2, "w": 8, "h": 8 },
   "yaxes": [
    { "format": "requests" }
   ],
   "targets": [
    {
     "expr": "sum(ray_serve_replica_processing_queries{deployment=~\"$Deployment\",replica=~\"$Replica\",}) by (deployment, replica)",
     "legendFormat": "{{replica}}"
    }
   ]
  }
 ]
}